{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18546,
          "sha512": "16116cc1a94028f716b02e7a0c9fec9dc09b5c214fd693912d566b4c8e364bb42d029548062f99efeb2c76f6b00b69fb1aee51ffbce3b213ef8589904e51cffb",
          "sha256": "e2bfe22157d8940981efe8c0aaea2d6cc53b172546224b4e957e89eb735211eb",
          "sha1": "766a3594d926344fef4d896f651e04725e25f20f",
          "md5": "32bc8cf9ae73e7aa3126aa8190adb1a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18546,
          "sha512": "16116cc1a94028f716b02e7a0c9fec9dc09b5c214fd693912d566b4c8e364bb42d029548062f99efeb2c76f6b00b69fb1aee51ffbce3b213ef8589904e51cffb",
          "sha256": "e2bfe22157d8940981efe8c0aaea2d6cc53b172546224b4e957e89eb735211eb",
          "sha1": "766a3594d926344fef4d896f651e04725e25f20f",
          "md5": "32bc8cf9ae73e7aa3126aa8190adb1a9"
        }
      ]
    }
  ]
}
