{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 17956,
          "sha512": "455495fe6a81ff907ea9358173b043cfac451a14fa1d2ebb56b909d2baa78ff07c8605199155dfee8c42dbd09164bc953f0c9599530837178f36f405176345b8",
          "sha256": "392357ac43a0d8f069a4faa2ebf186fb40f494667cc82554e2754e278473a83f",
          "sha1": "3ce078568eef983301d8094c9484c30e8ba865e9",
          "md5": "01a1043adda9bb69daa62b15f1cb1e7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 17956,
          "sha512": "455495fe6a81ff907ea9358173b043cfac451a14fa1d2ebb56b909d2baa78ff07c8605199155dfee8c42dbd09164bc953f0c9599530837178f36f405176345b8",
          "sha256": "392357ac43a0d8f069a4faa2ebf186fb40f494667cc82554e2754e278473a83f",
          "sha1": "3ce078568eef983301d8094c9484c30e8ba865e9",
          "md5": "01a1043adda9bb69daa62b15f1cb1e7c"
        }
      ]
    }
  ]
}
