{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 14869,
          "sha512": "b431ab404b5076480697063711f7a2be5dff11d87f2dfad7a9a0d7f75f872ed5e43babbfecb3745d98e1a005e8607139d9b43981177f86363abf1f0b41062508",
          "sha256": "17848899c1b600b1a57386ce8279ed64558d862f970a0747a087eef28b442e76",
          "sha1": "3e5363682557def1862d1e2a4eb3e6748b6e400a",
          "md5": "a1cb3a5d553033fba9b9f66cd4e478c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 14869,
          "sha512": "b431ab404b5076480697063711f7a2be5dff11d87f2dfad7a9a0d7f75f872ed5e43babbfecb3745d98e1a005e8607139d9b43981177f86363abf1f0b41062508",
          "sha256": "17848899c1b600b1a57386ce8279ed64558d862f970a0747a087eef28b442e76",
          "sha1": "3e5363682557def1862d1e2a4eb3e6748b6e400a",
          "md5": "a1cb3a5d553033fba9b9f66cd4e478c1"
        }
      ]
    }
  ]
}
