{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18690,
          "sha512": "2c26eb112969138bfd621d598ab25db8f205131adc502f2a68b3ac1c43cfa2200cef7433e3cd5b53e69b9966003de443aeca60785ef7f43a6cbadf0833920faf",
          "sha256": "a30d4c231d757d7bd1b85c0cf956e6e49bc25d264e02e150ea84869f1d12dd5e",
          "sha1": "264da9f73a0a76a24a36949f79d35ccc710b43b8",
          "md5": "3b4229a8b7f7bb6f566bc519f5e0b702"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18690,
          "sha512": "2c26eb112969138bfd621d598ab25db8f205131adc502f2a68b3ac1c43cfa2200cef7433e3cd5b53e69b9966003de443aeca60785ef7f43a6cbadf0833920faf",
          "sha256": "a30d4c231d757d7bd1b85c0cf956e6e49bc25d264e02e150ea84869f1d12dd5e",
          "sha1": "264da9f73a0a76a24a36949f79d35ccc710b43b8",
          "md5": "3b4229a8b7f7bb6f566bc519f5e0b702"
        }
      ]
    }
  ]
}
