{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18318,
          "sha512": "616695182db7f7268335f9b4594be915193bfaf623dd42b507ae4bfb8ef82a5c51225cdd21d753ef7c34f3491342d5e384a1f3108e1ca78dab471183766b2cac",
          "sha256": "b1a07169aa4835d36f3f447745f02c08fd61a3c51218f3052d5078ca2351a50d",
          "sha1": "f5a5645e25e0c5e215792ff038c7a0d8be8b8e66",
          "md5": "61cc8d36eb243f2b7dec6fd1487f512e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18318,
          "sha512": "616695182db7f7268335f9b4594be915193bfaf623dd42b507ae4bfb8ef82a5c51225cdd21d753ef7c34f3491342d5e384a1f3108e1ca78dab471183766b2cac",
          "sha256": "b1a07169aa4835d36f3f447745f02c08fd61a3c51218f3052d5078ca2351a50d",
          "sha1": "f5a5645e25e0c5e215792ff038c7a0d8be8b8e66",
          "md5": "61cc8d36eb243f2b7dec6fd1487f512e"
        }
      ]
    }
  ]
}
