{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18203,
          "sha512": "c1b7a5c01b435616e9b800878eeaca2be110931bf9e69dfcb44e2c5eaed84421645e5e5e96b6e1aded85bb37182776dad12776531f74df792fa73d2f3f5b668d",
          "sha256": "48ca83388223bf1cca59eab35a9e2b82b9108835ecc228ae2661c7b9ec65bbea",
          "sha1": "a9ea6c9ede946cfbb6a64b0098e178cbdbba2424",
          "md5": "d758d838038b7c5cadb7dde74edc1658"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18203,
          "sha512": "c1b7a5c01b435616e9b800878eeaca2be110931bf9e69dfcb44e2c5eaed84421645e5e5e96b6e1aded85bb37182776dad12776531f74df792fa73d2f3f5b668d",
          "sha256": "48ca83388223bf1cca59eab35a9e2b82b9108835ecc228ae2661c7b9ec65bbea",
          "sha1": "a9ea6c9ede946cfbb6a64b0098e178cbdbba2424",
          "md5": "d758d838038b7c5cadb7dde74edc1658"
        }
      ]
    }
  ]
}
