{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18601,
          "sha512": "0abeb020cb016e14db45e8d416186102d154dada9f757987ff4266315753197ecc75f4061fb96243e740d6ead968b99600b991b9b0ead38e0deb30c18aacf962",
          "sha256": "8b6f2eb0d0a1cb8d4527ec72eb88fb1f42134df325577055562512a55016bccc",
          "sha1": "6e5532a0c4ca81b6c89aacf146d072750aee6ace",
          "md5": "d099f9b193f0d18ecbc90c4d990db7a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18601,
          "sha512": "0abeb020cb016e14db45e8d416186102d154dada9f757987ff4266315753197ecc75f4061fb96243e740d6ead968b99600b991b9b0ead38e0deb30c18aacf962",
          "sha256": "8b6f2eb0d0a1cb8d4527ec72eb88fb1f42134df325577055562512a55016bccc",
          "sha1": "6e5532a0c4ca81b6c89aacf146d072750aee6ace",
          "md5": "d099f9b193f0d18ecbc90c4d990db7a4"
        }
      ]
    }
  ]
}
