{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 17953,
          "sha512": "ec08a7fa41d8370ccb46f0f724abb2bdda59140c50d49b4fc4f5c9652491c843efdf8a02c82040f65f043aa08228aaff3730f95517ecf6fe84dad16c11a38879",
          "sha256": "d5861cfd80e68f5f78e18b2b2b37e9f1c987fbcb779ed01d606822f9a6298387",
          "sha1": "c63fa3b614bf7dbbffc2ae6459f0a652d4e6d02c",
          "md5": "e11dec592cbcf0901c2396cbae0705c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 17953,
          "sha512": "ec08a7fa41d8370ccb46f0f724abb2bdda59140c50d49b4fc4f5c9652491c843efdf8a02c82040f65f043aa08228aaff3730f95517ecf6fe84dad16c11a38879",
          "sha256": "d5861cfd80e68f5f78e18b2b2b37e9f1c987fbcb779ed01d606822f9a6298387",
          "sha1": "c63fa3b614bf7dbbffc2ae6459f0a652d4e6d02c",
          "md5": "e11dec592cbcf0901c2396cbae0705c3"
        }
      ]
    }
  ]
}
