{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18811,
          "sha512": "85659eee2f07fa909f25c759f2a1cc340d7fbe9e450cc96006bdb1e8139d80c59059427969ab725068069b31f7e992964a63334b46e8bb46c255e33390e95fce",
          "sha256": "ab80d50d79a92564735de0c3f632a9bffeb08eb8090f44d71fa71f1538ef5e63",
          "sha1": "09402d08726c21aac9e06eb2a04afb2a47832fca",
          "md5": "018780b7dfc20060db5f524ee62407a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18811,
          "sha512": "85659eee2f07fa909f25c759f2a1cc340d7fbe9e450cc96006bdb1e8139d80c59059427969ab725068069b31f7e992964a63334b46e8bb46c255e33390e95fce",
          "sha256": "ab80d50d79a92564735de0c3f632a9bffeb08eb8090f44d71fa71f1538ef5e63",
          "sha1": "09402d08726c21aac9e06eb2a04afb2a47832fca",
          "md5": "018780b7dfc20060db5f524ee62407a0"
        }
      ]
    }
  ]
}
