{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 6304,
          "sha512": "9d57256e738b2983d0c31ded2b50ac5d1185d84dea864007769b20b7b2199a1cd385fc3f7afeffb8023692befdf602c97480f89073a26045721ce65317288e22",
          "sha256": "b98bd550a10a72538bfbe96688cf8653931d806e9d00eeb893ce465dcc64e6d9",
          "sha1": "ece4eea8ada605ab6e3a87006fe43ea688ef65a5",
          "md5": "a7a855b0356a233742283232cea17ed6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 6304,
          "sha512": "9d57256e738b2983d0c31ded2b50ac5d1185d84dea864007769b20b7b2199a1cd385fc3f7afeffb8023692befdf602c97480f89073a26045721ce65317288e22",
          "sha256": "b98bd550a10a72538bfbe96688cf8653931d806e9d00eeb893ce465dcc64e6d9",
          "sha1": "ece4eea8ada605ab6e3a87006fe43ea688ef65a5",
          "md5": "a7a855b0356a233742283232cea17ed6"
        }
      ]
    }
  ]
}
