{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 5155,
          "sha512": "1a7962a289b24b210dd6754990508584fdf437976e71546da5c1aaa0a3685e661a51ed304394bc5fc0f5e02ad009b7826698f008f69c63a980c2db71b7b55b9e",
          "sha256": "d60af31328954f19d3d18e6f970f033396c8313a752a7c16060503bf0348f12c",
          "sha1": "2917eefc0bfa815f054105f446eb2649b0fd074f",
          "md5": "14ce7b83bccd937a7c573a70956c37d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 5155,
          "sha512": "1a7962a289b24b210dd6754990508584fdf437976e71546da5c1aaa0a3685e661a51ed304394bc5fc0f5e02ad009b7826698f008f69c63a980c2db71b7b55b9e",
          "sha256": "d60af31328954f19d3d18e6f970f033396c8313a752a7c16060503bf0348f12c",
          "sha1": "2917eefc0bfa815f054105f446eb2649b0fd074f",
          "md5": "14ce7b83bccd937a7c573a70956c37d8"
        }
      ]
    }
  ]
}
