{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 10610,
          "sha512": "9440f299d81c11b2e718beb79fab3c9828cbbd2c1cd3018c12e289250c10c9860f7daf0caa6b4d86c87b0f3898810a9b9367c78d7f298fed36037effa26fa541",
          "sha256": "1069e5b4bf6b32befa158c4d1195b8eff7da65add403fc00eb8b0d8d4abcd7fb",
          "sha1": "ffa9fd120cd9bdb6e949469483c6a86b2469fa2d",
          "md5": "c46ba332abfffb0ce798255ed15a6165"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 10610,
          "sha512": "9440f299d81c11b2e718beb79fab3c9828cbbd2c1cd3018c12e289250c10c9860f7daf0caa6b4d86c87b0f3898810a9b9367c78d7f298fed36037effa26fa541",
          "sha256": "1069e5b4bf6b32befa158c4d1195b8eff7da65add403fc00eb8b0d8d4abcd7fb",
          "sha1": "ffa9fd120cd9bdb6e949469483c6a86b2469fa2d",
          "md5": "c46ba332abfffb0ce798255ed15a6165"
        }
      ]
    }
  ]
}
