{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 14726,
          "sha512": "4f9b57e729bf363e47b7710893db3aaee90530658eeec54162b20f72da732785c14c20c922f302238daa2ff3b9e686e6690ecd360b027bd84056caffdcb1e36d",
          "sha256": "9b90a995126d347cb8dd0302dd3c848def1b12c59973441a5d2f0b637723655e",
          "sha1": "1368fa555ae2904517e9fd3db2ba6f0c4aa5003f",
          "md5": "60264844c43474b8d8cfc1ad9dd3fa27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 14726,
          "sha512": "4f9b57e729bf363e47b7710893db3aaee90530658eeec54162b20f72da732785c14c20c922f302238daa2ff3b9e686e6690ecd360b027bd84056caffdcb1e36d",
          "sha256": "9b90a995126d347cb8dd0302dd3c848def1b12c59973441a5d2f0b637723655e",
          "sha1": "1368fa555ae2904517e9fd3db2ba6f0c4aa5003f",
          "md5": "60264844c43474b8d8cfc1ad9dd3fa27"
        }
      ]
    }
  ]
}
