{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 5169,
          "sha512": "fa6b8b5ef6af4252e1b356bb93fc783039805d5660c4e20bbd791000f2a57bb3dcca53491eb0e594ad02984d6dd5c65b49ca5d54c264f19854f7e186cbed64f8",
          "sha256": "6e06ec0d59bd04e7140ef42f07abe5ee8d3fa6ad7232b287dceff26624ab29f8",
          "sha1": "efb22b7580432e474a3205875ae493125ba4f274",
          "md5": "87cc1423131ad9b18efd2174ae678bba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 5169,
          "sha512": "fa6b8b5ef6af4252e1b356bb93fc783039805d5660c4e20bbd791000f2a57bb3dcca53491eb0e594ad02984d6dd5c65b49ca5d54c264f19854f7e186cbed64f8",
          "sha256": "6e06ec0d59bd04e7140ef42f07abe5ee8d3fa6ad7232b287dceff26624ab29f8",
          "sha1": "efb22b7580432e474a3205875ae493125ba4f274",
          "md5": "87cc1423131ad9b18efd2174ae678bba"
        }
      ]
    }
  ]
}
