{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 10613,
          "sha512": "464d2165d804c8176382ea52fea5118df69033e82198b8493e8bdb55159544fbcd015ff64a07b51087e5dbc82ec2c21ec1dea774e93d8d9c2cdeea60bf03f16c",
          "sha256": "16673a879e6a5948b639a7750ce2a9d11ad2f1a32d49c67f363ceb81658d49c8",
          "sha1": "0ee18f2dcafd65c07c2c1fe40de20421327e75f1",
          "md5": "32384f3f609c0efa76af68d52be30723"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 10613,
          "sha512": "464d2165d804c8176382ea52fea5118df69033e82198b8493e8bdb55159544fbcd015ff64a07b51087e5dbc82ec2c21ec1dea774e93d8d9c2cdeea60bf03f16c",
          "sha256": "16673a879e6a5948b639a7750ce2a9d11ad2f1a32d49c67f363ceb81658d49c8",
          "sha1": "0ee18f2dcafd65c07c2c1fe40de20421327e75f1",
          "md5": "32384f3f609c0efa76af68d52be30723"
        }
      ]
    }
  ]
}
