{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 13393,
          "sha512": "cdd4951d3d203e5f8f36ab58ca9e82f9834f848ca2415f2c0d3dcdd6426706159d893d9995a2b2392d0e8a32f5169c422e10d8335c0e1e1d2754afb4c76ae0ab",
          "sha256": "5555f385d93884a41341d90f5eea312580dfee78dd51efc765375ae58c50beed",
          "sha1": "354e0d5fdaf3d9558c7bbfc43bfabbfa757f8d65",
          "md5": "b3522500716b99a503a91fa3a85a23cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 13393,
          "sha512": "cdd4951d3d203e5f8f36ab58ca9e82f9834f848ca2415f2c0d3dcdd6426706159d893d9995a2b2392d0e8a32f5169c422e10d8335c0e1e1d2754afb4c76ae0ab",
          "sha256": "5555f385d93884a41341d90f5eea312580dfee78dd51efc765375ae58c50beed",
          "sha1": "354e0d5fdaf3d9558c7bbfc43bfabbfa757f8d65",
          "md5": "b3522500716b99a503a91fa3a85a23cc"
        }
      ]
    }
  ]
}
