{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 10610,
          "sha512": "1a30f11be08ac44b0d9bcf468a41f30c935ccabb4bcdf68abccdf7927a6666107fb4b0038413c40dc775b3014c8ace030406fa8d303d7a71ffe8218a3ad328c6",
          "sha256": "382b86db79417a0206bd9b4543000614d9c843fc82687acacd0b4ea3a680cebc",
          "sha1": "1573b4625fef2613f80a48bfa819ff90668177f9",
          "md5": "d9b211b78dc2111fb07d42089ec1ce90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 10610,
          "sha512": "1a30f11be08ac44b0d9bcf468a41f30c935ccabb4bcdf68abccdf7927a6666107fb4b0038413c40dc775b3014c8ace030406fa8d303d7a71ffe8218a3ad328c6",
          "sha256": "382b86db79417a0206bd9b4543000614d9c843fc82687acacd0b4ea3a680cebc",
          "sha1": "1573b4625fef2613f80a48bfa819ff90668177f9",
          "md5": "d9b211b78dc2111fb07d42089ec1ce90"
        }
      ]
    }
  ]
}
