{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 19268,
          "sha512": "cc2057f8272e37a754d1e9a78e49d1fd6a57d095ccba28136f88bbc457d163311a7a244bccbdcaa7d0acbe444346220f521c3a42217f2051a189702512f44c54",
          "sha256": "584873dd4b0d3b56fab29d3fac8abb2fb521672b177bfb057f0967dc1573b67c",
          "sha1": "054cb9907a4693e843ee6b3a883cb2c324f605b3",
          "md5": "87175dd295b6dd0fdf91d4ab58a88e42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 19268,
          "sha512": "cc2057f8272e37a754d1e9a78e49d1fd6a57d095ccba28136f88bbc457d163311a7a244bccbdcaa7d0acbe444346220f521c3a42217f2051a189702512f44c54",
          "sha256": "584873dd4b0d3b56fab29d3fac8abb2fb521672b177bfb057f0967dc1573b67c",
          "sha1": "054cb9907a4693e843ee6b3a883cb2c324f605b3",
          "md5": "87175dd295b6dd0fdf91d4ab58a88e42"
        }
      ]
    }
  ]
}
