{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 6308,
          "sha512": "02da4cc2897d697fc7a485fb554e573cb3f11a77cce7c4e8a146cc7867a3b927392140ebb2f87d4821ca6adeb6395abfda36939e41ade610a3b96819c64fa36e",
          "sha256": "a07e81df867d52953873c958dcf33f45c6bf7e1bdb1058526547ad271afb7cb2",
          "sha1": "6b579a68a50009869900cc73260af09ae0f2860b",
          "md5": "75c1c07203a6485611e5261a189a8554"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 6308,
          "sha512": "02da4cc2897d697fc7a485fb554e573cb3f11a77cce7c4e8a146cc7867a3b927392140ebb2f87d4821ca6adeb6395abfda36939e41ade610a3b96819c64fa36e",
          "sha256": "a07e81df867d52953873c958dcf33f45c6bf7e1bdb1058526547ad271afb7cb2",
          "sha1": "6b579a68a50009869900cc73260af09ae0f2860b",
          "md5": "75c1c07203a6485611e5261a189a8554"
        }
      ]
    }
  ]
}
