{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18943,
          "sha512": "4fa577f076f4617c835428e5a495dcddeb34e77a9962213083a318c334d74760126ba3460167c660026f76e860ad238fccdf12470f2059a3891703ce00ed1aa4",
          "sha256": "3564c7834b052ec5029b625068d65492b50288296937bbf5a166da307ce432aa",
          "sha1": "c892fda5b292505739942d9894ee78058353ddd6",
          "md5": "1bece8b92659801989aa2f7ee8957fe6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18943,
          "sha512": "4fa577f076f4617c835428e5a495dcddeb34e77a9962213083a318c334d74760126ba3460167c660026f76e860ad238fccdf12470f2059a3891703ce00ed1aa4",
          "sha256": "3564c7834b052ec5029b625068d65492b50288296937bbf5a166da307ce432aa",
          "sha1": "c892fda5b292505739942d9894ee78058353ddd6",
          "md5": "1bece8b92659801989aa2f7ee8957fe6"
        }
      ]
    }
  ]
}
