{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18870,
          "sha512": "935278a75271700c9e364d5a8a4913695a1e043ef93a832b5555fe8de94893131e73349e9a8c9487fd564c3d5d728ccbac28e5e99b82a0aeb496dec405d7a1e9",
          "sha256": "0024ee6e2425bf74213266073651b355e32da7f222f1d12332187d4916d0dde4",
          "sha1": "4d5641d089133fd9f295542fd89a2a9609e637fd",
          "md5": "a117165e7d476359e8c246fb71259ac7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18870,
          "sha512": "935278a75271700c9e364d5a8a4913695a1e043ef93a832b5555fe8de94893131e73349e9a8c9487fd564c3d5d728ccbac28e5e99b82a0aeb496dec405d7a1e9",
          "sha256": "0024ee6e2425bf74213266073651b355e32da7f222f1d12332187d4916d0dde4",
          "sha1": "4d5641d089133fd9f295542fd89a2a9609e637fd",
          "md5": "a117165e7d476359e8c246fb71259ac7"
        }
      ]
    }
  ]
}
