{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 5167,
          "sha512": "32305b6e17e7a1a9a9debe2aa214508655be34d1629d2caf98928ca160663d15b18feadc5b659477b3fa98f472b70a8b9d9475430f1f6185aafa0559b0a72105",
          "sha256": "28922fa14c7797c9955234e6c5cbe1673373404ef866817cf3363a42517aabb9",
          "sha1": "d2dc690327dead50f9f67b2ab0559e0778d2f3df",
          "md5": "c9cffa46309cda8dc6a16ae0020d5c22"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 5167,
          "sha512": "32305b6e17e7a1a9a9debe2aa214508655be34d1629d2caf98928ca160663d15b18feadc5b659477b3fa98f472b70a8b9d9475430f1f6185aafa0559b0a72105",
          "sha256": "28922fa14c7797c9955234e6c5cbe1673373404ef866817cf3363a42517aabb9",
          "sha1": "d2dc690327dead50f9f67b2ab0559e0778d2f3df",
          "md5": "c9cffa46309cda8dc6a16ae0020d5c22"
        }
      ]
    }
  ]
}
