{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18613,
          "sha512": "10e4b4ffdbecd9b612175892f339c68ba1fdd9b9596b2fb4147c1b3c894c77c92f879fb7a2b9458c0372a583a2039a838eaa36fe1b62c6b404c791380974f29d",
          "sha256": "f4368f0c0f66bfac0c307a27cac32c3637ea1360ce2e7a1701d7295a242cd706",
          "sha1": "82e68361eb2ee9451e69043c13a9e47f6faa536b",
          "md5": "779104f3849bbef292b679fb5d3f92c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18613,
          "sha512": "10e4b4ffdbecd9b612175892f339c68ba1fdd9b9596b2fb4147c1b3c894c77c92f879fb7a2b9458c0372a583a2039a838eaa36fe1b62c6b404c791380974f29d",
          "sha256": "f4368f0c0f66bfac0c307a27cac32c3637ea1360ce2e7a1701d7295a242cd706",
          "sha1": "82e68361eb2ee9451e69043c13a9e47f6faa536b",
          "md5": "779104f3849bbef292b679fb5d3f92c1"
        }
      ]
    }
  ]
}
