{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18784,
          "sha512": "c6405ea90a681ad13b9bbddc872a13b15829893ce5c21fce669ede82c628e48485072ae704f4a8149417c48bda5441898e384294867da75edbd76f13dd2aac35",
          "sha256": "8f29d3314f70537265f3283d3fa854391ae3ae6db2b65ad396837d0c30993a86",
          "sha1": "57a1dd5280877bb4022174dfc7d19c923f45bb9f",
          "md5": "116f12b727dd21ed4dc20d60ecb4c081"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18784,
          "sha512": "c6405ea90a681ad13b9bbddc872a13b15829893ce5c21fce669ede82c628e48485072ae704f4a8149417c48bda5441898e384294867da75edbd76f13dd2aac35",
          "sha256": "8f29d3314f70537265f3283d3fa854391ae3ae6db2b65ad396837d0c30993a86",
          "sha1": "57a1dd5280877bb4022174dfc7d19c923f45bb9f",
          "md5": "116f12b727dd21ed4dc20d60ecb4c081"
        }
      ]
    }
  ]
}
