{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 19908,
          "sha512": "399421257898c69a5dff22b742f571e348615f3f57db75dc74dba1cf8b014d16777cc6ac2fa400522920f42a2e2ad10a266bf8ab2ac51bbb8ed321c232a1e398",
          "sha256": "859c6b82cdebcd8de5a538a47b598c881e4897552e305a4cf2170f9f3acc905e",
          "sha1": "fe16471084b3c0d27314c0680881dd7f22d31b03",
          "md5": "65a82437ade670c0babd368365b88e5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 19908,
          "sha512": "399421257898c69a5dff22b742f571e348615f3f57db75dc74dba1cf8b014d16777cc6ac2fa400522920f42a2e2ad10a266bf8ab2ac51bbb8ed321c232a1e398",
          "sha256": "859c6b82cdebcd8de5a538a47b598c881e4897552e305a4cf2170f9f3acc905e",
          "sha1": "fe16471084b3c0d27314c0680881dd7f22d31b03",
          "md5": "65a82437ade670c0babd368365b88e5d"
        }
      ]
    }
  ]
}
