{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 21075,
          "sha512": "5dcc0d8fe101a8e585730c3d587220b61960796fa5c9abdb9fd88ce8cbb7fb3806110aef5f6431ad30c5dc9adf46b3ce4240591692f8cc42105146548d3cb6f0",
          "sha256": "68a534f11e983f322f0fd6ae63f8e7d6aeb03b30be74e11c22aad7efbb6e9f57",
          "sha1": "d91d4f2e1d80e8057b1a9772bb74947ed8ee4239",
          "md5": "aa51b3f8c8b6d0f5ffcd0e7bcd31e47d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 21075,
          "sha512": "5dcc0d8fe101a8e585730c3d587220b61960796fa5c9abdb9fd88ce8cbb7fb3806110aef5f6431ad30c5dc9adf46b3ce4240591692f8cc42105146548d3cb6f0",
          "sha256": "68a534f11e983f322f0fd6ae63f8e7d6aeb03b30be74e11c22aad7efbb6e9f57",
          "sha1": "d91d4f2e1d80e8057b1a9772bb74947ed8ee4239",
          "md5": "aa51b3f8c8b6d0f5ffcd0e7bcd31e47d"
        }
      ]
    }
  ]
}
