{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18737,
          "sha512": "7f06216d0b9578f5adc9d82b1258fdf98bab01322af0ed9e047136bf69878153b0bfcbd814c510eba71507dbf68fb379a784a60e5c049b73ab61f6e7c0a6669e",
          "sha256": "3b58cd2edaaed7aa18b7f0ff2ec51a13e7a50d74aaf2dd4345702a3e2e109bdd",
          "sha1": "c355c4f1d9ba6c7cc61bc24ed536fd7cd32787ae",
          "md5": "19ca947801e7abafc4c855080c68f075"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18737,
          "sha512": "7f06216d0b9578f5adc9d82b1258fdf98bab01322af0ed9e047136bf69878153b0bfcbd814c510eba71507dbf68fb379a784a60e5c049b73ab61f6e7c0a6669e",
          "sha256": "3b58cd2edaaed7aa18b7f0ff2ec51a13e7a50d74aaf2dd4345702a3e2e109bdd",
          "sha1": "c355c4f1d9ba6c7cc61bc24ed536fd7cd32787ae",
          "md5": "19ca947801e7abafc4c855080c68f075"
        }
      ]
    }
  ]
}
