{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 12482,
          "sha512": "fa86192e9cf5b86f4e15c7dd135e1182b684c0ebfcb2d0c841aad5e1200a6f6f295a50190346104b05e750429411ec0f11710d0715d02eb78449fdb2d9a4f320",
          "sha256": "c0711b06163f1d2d7add090c06b69390dbc29d486234784f4488cb582fcc8f29",
          "sha1": "1e595b0d4500df990c26580ea2a6ed5964fb7726",
          "md5": "84396ee02b8a6f4e34e364b3ce8a189c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 12482,
          "sha512": "fa86192e9cf5b86f4e15c7dd135e1182b684c0ebfcb2d0c841aad5e1200a6f6f295a50190346104b05e750429411ec0f11710d0715d02eb78449fdb2d9a4f320",
          "sha256": "c0711b06163f1d2d7add090c06b69390dbc29d486234784f4488cb582fcc8f29",
          "sha1": "1e595b0d4500df990c26580ea2a6ed5964fb7726",
          "md5": "84396ee02b8a6f4e34e364b3ce8a189c"
        }
      ]
    }
  ]
}
