{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 24470,
          "sha512": "2540ce2ee95ceecbbd388a7614ff5b0f0c7ece2fe170666709e74a423e4778213e17609ae3872814ec1b7ded78b7fda9b973eea9c1f51cab31780d4ee7d9ea1d",
          "sha256": "aec6633c619276ab70129f4a9e003bb5a2fc79e1e2249e93548e2c9076d276d1",
          "sha1": "0974deed73555dcea575af7621d4c90bd0feed41",
          "md5": "05ea19ac2e9ed9dfd36b11ecf81600c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 24470,
          "sha512": "2540ce2ee95ceecbbd388a7614ff5b0f0c7ece2fe170666709e74a423e4778213e17609ae3872814ec1b7ded78b7fda9b973eea9c1f51cab31780d4ee7d9ea1d",
          "sha256": "aec6633c619276ab70129f4a9e003bb5a2fc79e1e2249e93548e2c9076d276d1",
          "sha1": "0974deed73555dcea575af7621d4c90bd0feed41",
          "md5": "05ea19ac2e9ed9dfd36b11ecf81600c1"
        }
      ]
    }
  ]
}
