{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18743,
          "sha512": "641e9ae01c85f36b98e1059f496681183d54b6a9673f932636cfa27fca426b1833b8aba10d093876a20a3988548daf5eccc8f734d12ed903d6eda65b1f11eec3",
          "sha256": "a83ec9bf7cac17fab8546a9328473d7ea24b4352b86224132e942c1016863e0c",
          "sha1": "11155ba2416f852bffeaf0105a42954b23ee441e",
          "md5": "912981214d897e3dcd8aac01ccdc5980"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18743,
          "sha512": "641e9ae01c85f36b98e1059f496681183d54b6a9673f932636cfa27fca426b1833b8aba10d093876a20a3988548daf5eccc8f734d12ed903d6eda65b1f11eec3",
          "sha256": "a83ec9bf7cac17fab8546a9328473d7ea24b4352b86224132e942c1016863e0c",
          "sha1": "11155ba2416f852bffeaf0105a42954b23ee441e",
          "md5": "912981214d897e3dcd8aac01ccdc5980"
        }
      ]
    }
  ]
}
