{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18951,
          "sha512": "367d58c5f142881d289f1051460194a0e1457d1c62f159ac0abf655500dbecb45d864bcd0368b54ac97abbcc48e2695abb97e018e42d16c52883872c14b1ce52",
          "sha256": "980b0b88787ecd01bd7eb224ec75d6b44888e32df4082a154c58c5b7df1f5569",
          "sha1": "039a3e77068b7ec6cfae01e25353630aaf7f4a8d",
          "md5": "1d2fb1033daf01322670778f4cd295fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18951,
          "sha512": "367d58c5f142881d289f1051460194a0e1457d1c62f159ac0abf655500dbecb45d864bcd0368b54ac97abbcc48e2695abb97e018e42d16c52883872c14b1ce52",
          "sha256": "980b0b88787ecd01bd7eb224ec75d6b44888e32df4082a154c58c5b7df1f5569",
          "sha1": "039a3e77068b7ec6cfae01e25353630aaf7f4a8d",
          "md5": "1d2fb1033daf01322670778f4cd295fb"
        }
      ]
    }
  ]
}
