{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18995,
          "sha512": "f90cd065ecac9d7d7472d95cd31c4daa970b8fe6890df034552b9c7740bda46807cabbdde7140c436f35f3afd2663d7ef7c5354b1c4fe542a6ed349de5489417",
          "sha256": "127ed542cd4bbb3d4af6166729bbaeea59a65d72eb439b53fd7c520cd6e270ba",
          "sha1": "16a69193529e7d9ccc48f36db1251d88590116e3",
          "md5": "e2779f174adc3b5e331ff989a51bac51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 18995,
          "sha512": "f90cd065ecac9d7d7472d95cd31c4daa970b8fe6890df034552b9c7740bda46807cabbdde7140c436f35f3afd2663d7ef7c5354b1c4fe542a6ed349de5489417",
          "sha256": "127ed542cd4bbb3d4af6166729bbaeea59a65d72eb439b53fd7c520cd6e270ba",
          "sha1": "16a69193529e7d9ccc48f36db1251d88590116e3",
          "md5": "e2779f174adc3b5e331ff989a51bac51"
        }
      ]
    }
  ]
}
