{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 20239,
          "sha512": "b942152f45516425e228731867225d103315e865ec2bea533a68a25d965fe28d57b6ae9903b6048a46c69118dac0cad97ed3e27e53f7cac9b1584ecb7e3478df",
          "sha256": "1d43a319de0101c4cc2b61ebbf8360bf74ebf05879e84453a091e0b27e4b91ff",
          "sha1": "da1457e47536bb303d3c66801c01cbf4583ec839",
          "md5": "b184b4537c39b31c67fb07051adc0b5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 20239,
          "sha512": "b942152f45516425e228731867225d103315e865ec2bea533a68a25d965fe28d57b6ae9903b6048a46c69118dac0cad97ed3e27e53f7cac9b1584ecb7e3478df",
          "sha256": "1d43a319de0101c4cc2b61ebbf8360bf74ebf05879e84453a091e0b27e4b91ff",
          "sha1": "da1457e47536bb303d3c66801c01cbf4583ec839",
          "md5": "b184b4537c39b31c67fb07051adc0b5b"
        }
      ]
    }
  ]
}
