{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 25101,
          "sha512": "6fbf22f7c37cab49f14a4f3dcb34c47169df36f5a298c4a5157ac522003ae247e296439262e2d48fd53a25168ee1a129d8ef0c307334021cdf892692fc87e04b",
          "sha256": "280c79edf3e6758d2d94462c5d26f0c07e6355fe36532055a3ae24ee806e44db",
          "sha1": "409f27625a1e381526d93bfa893cfb7f2d225519",
          "md5": "67503ccf9d4a848bd11b209bbc68490b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 25101,
          "sha512": "6fbf22f7c37cab49f14a4f3dcb34c47169df36f5a298c4a5157ac522003ae247e296439262e2d48fd53a25168ee1a129d8ef0c307334021cdf892692fc87e04b",
          "sha256": "280c79edf3e6758d2d94462c5d26f0c07e6355fe36532055a3ae24ee806e44db",
          "sha1": "409f27625a1e381526d93bfa893cfb7f2d225519",
          "md5": "67503ccf9d4a848bd11b209bbc68490b"
        }
      ]
    }
  ]
}
