{
  "formatVersion": "1.1",
  "component": {
    "group": "com.projreport",
    "module": "ProjReport",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 19305,
          "sha512": "19e8d57cb51dcd789ce0d09b9fbcb43cffb730c60de60d938c4e472e21d3dfa94585c78e54e350a56474b9cce6942d7721b009aafb740f4435c988ed48bf04ad",
          "sha256": "9f00b6ea98ab2cd50b07e8075a18cc2c06072e935fddd739f4cd3bdf5293d8a3",
          "sha1": "d1627cc634b63c2d5e471406a92c0016e48ea22a",
          "md5": "74655d07b6239d4880b2934ef5f7e30d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjReport-1.0-SNAPSHOT.jar",
          "url": "ProjReport-1.0-SNAPSHOT.jar",
          "size": 19305,
          "sha512": "19e8d57cb51dcd789ce0d09b9fbcb43cffb730c60de60d938c4e472e21d3dfa94585c78e54e350a56474b9cce6942d7721b009aafb740f4435c988ed48bf04ad",
          "sha256": "9f00b6ea98ab2cd50b07e8075a18cc2c06072e935fddd739f4cd3bdf5293d8a3",
          "sha1": "d1627cc634b63c2d5e471406a92c0016e48ea22a",
          "md5": "74655d07b6239d4880b2934ef5f7e30d"
        }
      ]
    }
  ]
}
