name: Run Gradle on PRs
on: pull_request
jobs:


  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: tearing
          java-version: 11
          gradle-version: 7.4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

  gradle-rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: tearing
          java-version: 11
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - run: gradle build --dry-run # just test build configuration